version: 2.1
 
orbs:
  ruby: circleci/ruby@1.2
 
jobs:
  test:
    parameters:
      ruby-image:
        type: string
    docker:
      - image: << parameters.ruby-image >>
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install bundler gem
          command: gem install bundler --version '~> 2.2'
      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install
      - ruby/rubocop-check
      - ruby/rspec-test
  coverage:
    docker:
      - image: cimg/ruby:3.0
    resource_class: small
    environment:
      COVERAGE: true
    steps:
      - checkout
      - run:
          name: Install bundler gem
          command: gem install bundler --version '~> 2.2'
      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install
      - run:
          name: Run tests with Simplecov enabled
          command: bundle exec rspec spec
      - store_artifacts:
          path: coverage
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-image: ["cimg/ruby:2.6", "cimg/ruby:2.7", "cimg/ruby:3.0", "ruby:3.1.0-preview1"]
      - coverage
