version: 2.1
 
orbs:
  ruby: circleci/ruby@1.2
 
jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check
      - ruby/rspec-test
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.6", "2.7", "2.9", "2.9", "3.0"]
