name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    name: Docs

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .downloaded-cache
          key: downloaded-cache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.1
          bundler-cache: true
          bundler: default
      - name: Build documentation with Yard
        run: bundle exec yard

  rubocop:
    name: RuboCop

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .downloaded-cache
          key: downloaded-cache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.1
          bundler-cache: true
          bundler: default
      - name: Run RuboCop
        run: bundle exec rubocop

  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby-2.6
          - ruby-2.7
          - ruby-3.0
          - ruby-3.1

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .downloaded-cache
          key: downloaded-cache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: default
      - name: Run RSpec tests
        run: bundle exec rspec
