name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    name: RuboCop

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .downloaded-cache
          key: downloaded-cache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.1
          bundler-cache: true
          bundler: default
      - name: Run RuboCop
        run: bundle exec rubocop
